### ISSUE TITLE
optional role to edit fields

### ISSUE THREAD

**Issue by facascante** [CityWebConsultants/Iris#197] opened 2016-04-27 14:16 UTC
currently, when you add/edit a field within an entity type. There are ‘view permissions’ where you  choose which roles can view this field.

It would be good if there was the option to choose which roles could ‘edit’ those fields. So for example, in user profiles the users ‘role’ is a field. But only admins should be able to edit that field

**Comment by FilipNest** [comment] 2016-04-27 14:26
This is a duplicate of https://github.com/CityWebConsultants/Iris/issues/133

**Closed as completed** 2016-04-27 14:50 UTC
